version: '3'

services:
  frontend:
    image: note-web-app-client
    build: 
      context: ./note-web-app-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    image: note-web-app-ws
    build: 
      context: ./note-web-app-ws
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DATABASE_URL: "jdbc:mysql://database:3306/note_web_app_db"
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: "note_web_app_db"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: always 